rem Clear files after swag is generated by SwaggerHub,
rem otherwise they will interfere with docker-compose
@echo off

del build.bat
del build.sh
del "IO.Swagger.sln"
del global.json

del "src\IO.Swagger\IO.Swagger.xproj"
del "src\IO.Swagger\project.json"
